CREATE TABLE tenant
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_name VARCHAR(255),
    identifier  VARCHAR(255)                            NOT NULL,
    status      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tenant PRIMARY KEY (id)
);

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255),
    password  VARCHAR(255)                            NOT NULL,
    role      VARCHAR(255),
    email     VARCHAR(255)                            NOT NULL,
    tenant_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE tenant
    ADD CONSTRAINT uc_tenant_identifier UNIQUE (identifier);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant (id);