CREATE TABLE booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    price      DECIMAL,
    quantity   BIGINT,
    user_id    BIGINT,
    event_id   BIGINT,
    seat_id    BIGINT,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE event
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    title            VARCHAR(255),
    event_start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time         TIMESTAMP WITHOUT TIME ZONE,
    address          VARCHAR(255),
    created_by_id    BIGINT,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE seat
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version       BIGINT,
    event_id      BIGINT,
    seat_status   VARCHAR(255),
    row_number    INTEGER                                 NOT NULL,
    column_number INTEGER                                 NOT NULL,
    seat_number   VARCHAR(255),
    price         DECIMAL,
    CONSTRAINT pk_seat PRIMARY KEY (id)
);

CREATE TABLE tenant
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_name VARCHAR(255),
    identifier  VARCHAR(255)                            NOT NULL,
    status      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tenant PRIMARY KEY (id)
);

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255),
    password  VARCHAR(255)                            NOT NULL,
    role      VARCHAR(255),
    email     VARCHAR(255)                            NOT NULL,
    tenant_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE tenant
    ADD CONSTRAINT uc_tenant_identifier UNIQUE (identifier);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE booking
    ADD CONSTRAINT FK_BOOKING_ON_SEAT FOREIGN KEY (seat_id) REFERENCES seat (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_CREATEDBY FOREIGN KEY (created_by_id) REFERENCES users (id);

ALTER TABLE seat
    ADD CONSTRAINT FK_SEAT_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant (id);